name: agro_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_barcode_scanner: ^2.0.0
  firebase_auth: any
  cloud_firestore: any
  provider: any
  flutter_spinkit: any
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  firebase_core: ^3.5.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.2
  qr_flutter: ^4.0.0
  screenshot: ^3.0.0
  pretty_qr_code: ^3.3.0
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: JotiOne
      fonts:
        - asset: lib/fonts/JotiOne-Regular.ttf

  assets:
    - lib\resources\images\animal.jpg